# Generated by Django 5.2.5 on 2025-08-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=64, unique=True)),
                ('is_subscribed', models.BooleanField(default=True)),
                ('state', models.CharField(blank=True, max_length=32)),
                ('temp_type', models.CharField(blank=True, max_length=8)),
                ('temp_asset', models.CharField(blank=True, max_length=50)),
                ('temp_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('temp_order_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
