# Generated by Django 5.2.5 on 2025-09-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_botuser_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='temp_query_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
