# Generated by Django 5.2.5 on 2025-09-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_vendor_avatar_bankdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='external_vendor_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_service_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='last_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='last_payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='last_payment_currency',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='last_payment_network',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='last_payment_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='last_payment_tx_hash',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='plan',
            field=models.CharField(choices=[('trial', 'Trial'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('perpetual', 'Perpetual'), ('none', 'None')], default='trial', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='trial_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
