# Generated by Django 5.2.5 on 2025-09-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_vendor_external_vendor_id_vendor_is_service_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='unavailable_message',
            field=models.TextField(blank=True),
        ),
    ]
