# Generated by Django 5.2.5 on 2025-09-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_vendor_telegram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='wallet_chain',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
