# Generated by Django 5.2.5 on 2025-09-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add_auto_accept_to_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPaymentDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('bank', 'Bank Account'), ('crypto', 'Crypto Address'), ('other', 'Other')], default='bank', max_length=20)),
                ('details', models.TextField(help_text='Full details to show to vendors (account number, instructions, address, memo, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
