# Generated by Django 5.2.5 on 2025-09-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_globalpaymentdestination'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='daily_orders_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='daily_orders_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
