# Generated by Django 5.2.5 on 2025-09-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_vendor_daily_orders_count_vendor_daily_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='plan',
            field=models.CharField(choices=[('trial', 'Trial'), ('none', 'Free Plan'), ('monthly', 'Monthly'), ('quarterly', '3-Month Plan'), ('semi-annual', '6-Month Plan'), ('yearly', 'Annual Plan'), ('perpetual', 'Perpetual')], default='trial', max_length=20),
        ),
    ]
