# Generated by Django 5.2.5 on 2025-09-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_vendor_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='daily_order_limit',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
