
services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env.prod
    command: gunicorn vendora.wsgi:application -w 3 -b 0.0.0.0:8000 --timeout 120
    working_dir: /app/backend
    volumes:
      - ./backend/media:/app/backend/media
      - ./backend/static:/app/backend/static
    expose:
      - "8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/healthz/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

  scheduler:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env.prod
    command: sh -c "while true; do echo '[scheduler] Expiring licenses and orders'; python manage.py expire_licenses && python manage.py expire_orders; sleep 3600; done"
    working_dir: /app/backend
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
