# Generated by Django 5.2.5 on 2025-09-12 00:00
from django.db import migrations


def add_columns_if_missing(apps, schema_editor):
    # Idempotent add of accepted_at and declined_at to orders_order
    table = 'orders_order'
    conn = schema_editor.connection
    try:
        with conn.cursor() as cursor:
            try:
                cursor.execute(f"PRAGMA table_info('{table}')")
                cols = [row[1] for row in cursor.fetchall()]  # 2nd item is column name
            except Exception:
                cols = []
            if 'accepted_at' not in cols:
                try:
                    cursor.execute(f'ALTER TABLE "{table}" ADD COLUMN "accepted_at" datetime NULL')
                except Exception:
                    pass
            if 'declined_at' not in cols:
                try:
                    cursor.execute(f'ALTER TABLE "{table}" ADD COLUMN "declined_at" datetime NULL')
                except Exception:
                    pass
    except Exception:
        # As a fallback, try using schema_editor on historical model (portable approach)
        try:
            from django.db import models
            Order = apps.get_model('orders', 'Order')
            if not any(f.name == 'accepted_at' for f in Order._meta.get_fields()):
                field = models.DateTimeField(null=True, blank=True)
                field.set_attributes_from_name('accepted_at')
                try:
                    schema_editor.add_field(Order, field)
                except Exception:
                    pass
            if not any(f.name == 'declined_at' for f in Order._meta.get_fields()):
                field = models.DateTimeField(null=True, blank=True)
                field.set_attributes_from_name('declined_at')
                try:
                    schema_editor.add_field(Order, field)
                except Exception:
                    pass
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_order_code_order_pay_instructions_and_more'),
    ]

    operations = [
        migrations.RunPython(add_columns_if_missing, migrations.RunPython.noop),
    ]
