# Generated by Django 5.2.5 on 2025-09-12 00:00
from django.db import migrations


def add_columns_if_missing(apps, schema_editor):
    # Idempotent add of accepted_at and declined_at to orders_order
    from django.db import models
    
    try:
        Order = apps.get_model('orders', 'Order')
        
        # Use Django's database introspection to check for existing columns
        # This is portable across all database backends
        table_name = Order._meta.db_table
        introspection = schema_editor.connection.introspection
        
        with schema_editor.connection.cursor() as cursor:
            # Get existing column names using Django's database introspection
            existing_columns = [
                column.name for column in introspection.get_table_description(cursor, table_name)
            ]
            
            # Add accepted_at column if it doesn't exist
            if 'accepted_at' not in existing_columns:
                field = models.DateTimeField(null=True, blank=True)
                field.set_attributes_from_name('accepted_at')
                try:
                    schema_editor.add_field(Order, field)
                except Exception:
                    # Column might already exist from previous run
                    pass
            
            # Add declined_at column if it doesn't exist
            if 'declined_at' not in existing_columns:
                field = models.DateTimeField(null=True, blank=True)
                field.set_attributes_from_name('declined_at')
                try:
                    schema_editor.add_field(Order, field)
                except Exception:
                    # Column might already exist from previous run
                    pass
    except Exception:
        # If anything fails, silently continue - the columns will be added by migration 0007
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_order_code_order_pay_instructions_and_more'),
    ]

    operations = [
        migrations.RunPython(add_columns_if_missing, migrations.RunPython.noop),
    ]
