# Generated by Django 5.2.5 on 2025-09-12 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_accepted_at_order_declined_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['vendor', 'status', 'created_at'], name='ord_vsc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='ord_sc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='ord_c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['auto_expire_at'], name='ord_exp_idx'),
        ),
    ]
