spec:
  name: vendora-unified
  services:
  # Backend API service
  - name: backend
    source_dir: backend
    github:
      repo: Donsirmuel/Vendora-Unified
      branch: main
      deploy_on_push: true
  # Use Gunicorn with Uvicorn worker for ASGI; include worker tmp dir to avoid /tmp tmpfs issues
  run_command: gunicorn vendora.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080 --workers 1 --timeout 120 --worker-tmp-dir /dev/shm
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    health_check:
      http_path: /api/v1/health/
    envs:
    - key: DIGITALOCEAN_APP_PLATFORM
      value: "true"
    - key: DEBUG
      value: "false"
    - key: DJANGO_SETTINGS_MODULE
      value: "vendora.settings"
    - key: SECRET_KEY
      scope: RUN_TIME
      type: SECRET
    - key: DATABASE_URL
      scope: RUN_TIME
      type: SECRET
    - key: ALLOWED_HOSTS
      value: "api.vendora.page,vendora.page"
    - key: CSRF_TRUSTED_ORIGINS
      value: "https://api.vendora.page,https://app.vendora.page"
    - key: PRODUCTION_CORS_ORIGINS
      value: "https://app.vendora.page,https://vendora.page"
    - key: TELEGRAM_BOT_TOKEN
      scope: RUN_TIME
      type: SECRET
    - key: TELEGRAM_BOT_USERNAME
      value: "VendoraUnifiedBot"
    - key: TELEGRAM_WEBHOOK_URL
      value: "https://api.vendora.page/api/v1/telegram/webhook/"
    - key: TELEGRAM_WEBHOOK_SECRET
      scope: RUN_TIME
      type: SECRET
    - key: FRONTEND_URL
      value: "https://app.vendora.page"
    
  # Frontend static site
  - name: frontend
    source_dir: frontend
    github:
      repo: Donsirmuel/Vendora-Unified
      branch: main
      deploy_on_push: true
    build_command: npm ci --prefer-offline --no-audit --no-fund && NODE_OPTIONS="--max-old-space-size=2048 --max-semi-space-size=128" npm run build
    output_dir: dist
    environment_slug: node-js
    instance_count: 1
  instance_size_slug: apps-s-2vcpu-2gb
    envs:
    - key: VITE_API_BASE
      value: "https://api.vendora.page"
    - key: VITE_WS_PROTOCOL
      value: "wss"
    - key: VITE_API_HOST
      value: "api.vendora.page"

  domains:
  - name: api.vendora.page
    type: PRIMARY
    zone: vendora.page
  - name: app.vendora.page
    type: ALIAS
    zone: vendora.page