spec:
  name: vendora-unified
  # GitHub source configuration - applies to all services
  github:
    repo: Donsirmuel/Vendora-Unified
    branch: main
    deploy_on_push: true
  
  services:
  # Backend API service
  - name: backend
    source_dir: backend
    # Procfile in backend/ directory defines the start command
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    health_check:
      http_path: /health/
    envs:
    - key: DIGITALOCEAN_APP_PLATFORM
      value: "true"
    - key: DEBUG
      value: "false"
    - key: DJANGO_SETTINGS_MODULE
      value: "vendora.settings"
    - key: SECRET_KEY
      scope: RUN_TIME
      type: SECRET
    - key: DATABASE_URL
      scope: RUN_TIME
      type: SECRET
    - key: ALLOWED_HOSTS
      value: "api.vendora.page,vendora.page"
    - key: CSRF_TRUSTED_ORIGINS
      value: "https://api.vendora.page,https://app.vendora.page"
    - key: PRODUCTION_CORS_ORIGINS
      value: "https://app.vendora.page,https://vendora.page"
    - key: TELEGRAM_BOT_TOKEN
      scope: RUN_TIME
      type: SECRET
    - key: TELEGRAM_BOT_USERNAME
      value: "VendoraUnifiedBot"
    - key: TELEGRAM_WEBHOOK_URL
      value: "https://api.vendora.page/api/v1/telegram/webhook/"
    - key: TELEGRAM_WEBHOOK_SECRET
      scope: RUN_TIME
      type: SECRET
    - key: FRONTEND_URL
      value: "https://app.vendora.page"
    
  # Frontend static site (use DigitalOcean static_site type)
  - name: frontend
    type: static
    source_dir: frontend
    # Frontend build is now handled by GitHub Actions (see .github/workflows/frontend-build.yml).
    # Keep build_command here as a fallback; you can later replace with a lightweight copy
    # step if you introduce artifact download.
    build_command: npm ci --prefer-offline --no-audit && npm run build
    output_dir: dist
    envs:
    - key: VITE_API_BASE
      value: "https://api.vendora.page"
    - key: VITE_WS_PROTOCOL
      value: "wss"
    - key: VITE_API_HOST
      value: "api.vendora.page"

  domains:
  - name: api.vendora.page
    type: PRIMARY
    zone: vendora.page
  - name: app.vendora.page
    type: ALIAS
    zone: vendora.page