spec:
  name: vendora-unified
  services:
  # Backend API service
  - name: backend
    source_dir: backend
    github:
      repo: Donsirmuel/Vendora-Unified
      branch: main
      deploy_on_push: true
    # Explicit run command (still honors Procfile steps inside start.sh)
    run_command: "bash start.sh"
    environment_slug: python
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-2gb
    http_port: 8080
    health_check:
      http_path: /health/
    envs:
    - key: DIGITALOCEAN_APP_PLATFORM
      value: "true"
    - key: DEBUG
      value: "false"
    - key: DJANGO_SETTINGS_MODULE
      value: "vendora.settings"
    - key: SECRET_KEY
      scope: RUN_TIME
      type: SECRET
    - key: DATABASE_URL
      scope: RUN_TIME
      type: SECRET
    - key: ALLOWED_HOSTS
      value: "api.vendora.page,app.vendora.page,vendora.page"
    - key: CSRF_TRUSTED_ORIGINS
      value: "https://api.vendora.page,https://app.vendora.page"
    - key: PRODUCTION_CORS_ORIGINS
      value: "https://app.vendora.page,https://vendora.page"
    - key: TELEGRAM_BOT_TOKEN
      scope: RUN_TIME
      type: SECRET
    - key: TELEGRAM_BOT_USERNAME
      value: "VendoraUnifiedBot"
    - key: TELEGRAM_WEBHOOK_URL
      value: "https://api.vendora.page/api/v1/telegram/webhook/"
    - key: TELEGRAM_WEBHOOK_SECRET
      scope: RUN_TIME
      type: SECRET
    - key: FRONTEND_URL
      value: "https://app.vendora.page"
    
  static_sites:
  - name: frontend
    github:
      repo: Donsirmuel/Vendora-Unified
      branch: frontend-build-artifacts
      deploy_on_push: true
    source_dir: .
    output_dir: dist
    error_document: 404.html
    envs:
    - key: VITE_API_BASE
      value: "https://api.vendora.page"
    - key: VITE_WS_PROTOCOL
      value: "wss"
    - key: VITE_API_HOST
      value: "api.vendora.page"

  http:
    routes:
    - path: /
      source:
        type: SERVICE
        name: backend
    - path: /
      source:
        type: STATIC_SITE
        name: frontend

  domains:
  - name: api.vendora.page
    type: PRIMARY
    zone: vendora.page
    service_name: backend
  - name: app.vendora.page
    type: ALIAS
    zone: vendora.page
    service_name: frontend