# Generated by Django 5.2.5 on 2025-09-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'ordering': ['-timestamp', 'id']},
        ),
    ]
