# Generated by Django 5.2.5 on 2025-08-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_alter_rate_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='bank_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='contract_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
