# Generated by Django 5.2.5 on 2025-09-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_rate_bank_details_alter_rate_contract_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ['asset', 'id']},
        ),
    ]
