# Generated by Django 5.2.5 on 2025-08-27 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-completed_at', '-id']},
        ),
    ]
