# Generated by Django 5.2.5 on 2025-09-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_receiving_details',
            field=models.TextField(blank=True),
        ),
    ]
