# Generated by Django 5.2.5 on 2025-09-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_customer_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='vendor_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vendor_proof',
            field=models.FileField(blank=True, null=True, upload_to='vendor_proofs/'),
        ),
    ]
