# Generated by Django 5.2.5 on 2025-09-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_vendor_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('uncompleted', 'Uncompleted'), ('completed', 'Completed'), ('declined', 'Declined')], default='uncompleted', max_length=20),
        ),
    ]
