# Generated by Django 5.2.5 on 2025-09-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('uncompleted', 'Uncompleted'), ('completed', 'Completed'), ('declined', 'Declined'), ('expired', 'Expired')], default='uncompleted', max_length=20),
        ),
    ]
