# Generated by Django 5.2.5 on 2025-09-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_ord_vsc_idx_order_ord_sc_idx_order_ord_c_idx_and_more'),
        ('transactions', '0006_alter_transaction_proof_alter_transaction_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'completed_at'], name='txn_sc_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('order',), name='unique_transaction_per_order'),
        ),
    ]
