# Generated by assistant: add vendor_notified boolean field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0009_backfill_created_at_from_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="vendor_notified",
            field=models.BooleanField(default=False),
        ),
    ]
