name: Frontend Build (Artifact)

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-build.yml'
  workflow_dispatch: {}

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        working-directory: frontend
        run: |
          npm ci --prefer-offline --no-audit --no-fund

      - name: Build frontend
        working-directory: frontend
        env:
          VITE_API_BASE: ${{ secrets.VITE_API_BASE || 'https://api.vendora.page' }}
          VITE_API_HOST: ${{ secrets.VITE_API_HOST || 'api.vendora.page' }}
          VITE_WS_PROTOCOL: ${{ secrets.VITE_WS_PROTOCOL || 'wss' }}
        run: |
          NODE_OPTIONS=--max-old-space-size=4096 npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist-${{ github.sha }}
          path: frontend/dist
          retention-days: 7
      - name: Publish dist to frontend-build-artifacts branch
        env:
          TARGET_BRANCH: frontend-build-artifacts
        run: |
          set -e
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          # Fetch existing branch if present
          git fetch origin $TARGET_BRANCH || true
          # Create worktree for branch manipulation (safer than orphan wipe of root)
          git checkout -B $TARGET_BRANCH
          # Ensure frontend/dist exists (it does) and commit only that subtree + minimal files
          # Optionally prune old dist contents
          git add frontend/dist
          git commit -m "ci: update built frontend dist for ${GITHUB_SHA}" || echo "No changes to commit"
          git push origin $TARGET_BRANCH

      - name: Summary
        run: |
          echo "Frontend build complete. Artifact uploaded as frontend-dist-${GITHUB_SHA}" >> $GITHUB_STEP_SUMMARY
          echo "Published dist to branch: frontend-build-artifacts" >> $GITHUB_STEP_SUMMARY
